\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Detección de patrones en el uso de drogas},
            pdfauthor={Daniel Alejandro Cruz Pérez},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\providecommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{Detección de patrones en el uso de drogas}
    \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
    \author{Daniel Alejandro Cruz Pérez}
    \preauthor{\centering\large\emph}
  \postauthor{\par}
      \predate{\centering\large\emph}
  \postdate{\par}
    \date{13 de mayo de 2019}


\begin{document}
\maketitle

\section{RESUMEN}\label{resumen}

\section{PALABRAS CLAVE}\label{palabras-clave}

\section{INTRODUCCIÓN}\label{introduccion}

El dataset usado, en su mayoría de las variables presenta valores
booleanos, donde 0 representa ``No'' y 1 representa ``Si'', hay algunos
casos dónde la variable toma valores discretos entre 1 y 10, a
continuación se explican los valores discretos:

\begin{verbatim}
Ingresos personales (Por año en dólares) 
1.- Menos de $10,000
2.- $10,000 - $19,999
3.- $20,000 - $29,999
4.- $30,000 - $39,999
5.- $40,000 - $49,999
6.- $50,000 - $74,999
7.- Mas de $75,000
\end{verbatim}

\begin{verbatim}
Ingresos personales (Por año en dólares) 
1.- Menos de $10,000
2.- $10,000 - $19,999
3.- $20,000 - $29,999
4.- $30,000 - $39,999
5.- $40,000 - $49,999
6.- $50,000 - $74,999
7.- Mas de $75,000
\end{verbatim}

\begin{verbatim}
Estado laboral
1.- Tiempo completo
2.- Medio tiempo
3.- Desempleado
\end{verbatim}

\begin{verbatim}
Raza
1.- Blanco
2.- Afroamericano
3.- Nativo americano
4.- Hawaiano
5.- Asiático
6.- Mestizo
7.- Hispano
\end{verbatim}

\begin{verbatim}
Grado de estudios
1.- Menor a preparatoria
2.- Sólo preparatoria
3.- Carrera trunca
4.- Carrera terminada
5.- 12 a 17 años de edad
\end{verbatim}

\begin{verbatim}
Sexo
1.- Hombre
2.- Mujer
\end{verbatim}

\section{MARCO TEÓRICO}\label{marco-teorico}

\section{RESULTADOS}\label{resultados}

\subsection{Análisis sobre individuos que alguna vez han probado
drogas}\label{analisis-sobre-individuos-que-alguna-vez-han-probado-drogas}

\begin{verbatim}
##    marij_ever      cocaine_ever      crack_ever       heroin_ever     
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.00000   Min.   :0.00000  
##  1st Qu.:1.0000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.00000  
##  Median :1.0000   Median :0.0000   Median :0.00000   Median :0.00000  
##  Mean   :0.9235   Mean   :0.2734   Mean   :0.05768   Mean   :0.03476  
##  3rd Qu.:1.0000   3rd Qu.:1.0000   3rd Qu.:0.00000   3rd Qu.:0.00000  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.00000   Max.   :1.00000  
##  hallucinogen_ever inhalant_ever      meth_ever       painrelieve_ever
##  Min.   :0.00      Min.   :0.0000   Min.   :0.00000   Min.   :0.0000  
##  1st Qu.:0.00      1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000  
##  Median :0.00      Median :0.0000   Median :0.00000   Median :0.0000  
##  Mean   :0.34      Mean   :0.1962   Mean   :0.09947   Mean   :0.2325  
##  3rd Qu.:1.00      3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.0000  
##  Max.   :1.00      Max.   :1.0000   Max.   :1.00000   Max.   :1.0000  
##    tranq_ever      stimulant_ever   sedative_ever     countofdrugs_ever
##  Min.   :0.00000   Min.   :0.0000   Min.   :0.00000   Min.   :0.0000   
##  1st Qu.:0.00000   1st Qu.:0.0000   1st Qu.:0.00000   1st Qu.:0.0000   
##  Median :0.00000   Median :0.0000   Median :0.00000   Median :0.1111   
##  Mean   :0.09799   Mean   :0.1098   Mean   :0.04215   Mean   :0.1500   
##  3rd Qu.:0.00000   3rd Qu.:0.0000   3rd Qu.:0.00000   3rd Qu.:0.2222   
##  Max.   :1.00000   Max.   :1.0000   Max.   :1.00000   Max.   :1.0000   
##  PersonalIncome    FamilyIncome    EmploymentStatus    race_num     
##  Min.   :0.0000   Min.   :0.0000   Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.1667   1st Qu.:0.3333   1st Qu.:0.0000   1st Qu.:0.0000  
##  Median :0.3333   Median :0.8333   Median :0.0000   Median :0.0000  
##  Mean   :0.4138   Mean   :0.6614   Mean   :0.1933   Mean   :0.2219  
##  3rd Qu.:0.6667   3rd Qu.:1.0000   3rd Qu.:0.5000   3rd Qu.:0.1667  
##  Max.   :1.0000   Max.   :1.0000   Max.   :1.0000   Max.   :1.0000  
##    education           sex        
##  Min.   :0.0000   Min.   :0.0000  
##  1st Qu.:0.3333   1st Qu.:0.0000  
##  Median :0.6667   Median :0.0000  
##  Mean   :0.6091   Mean   :0.4882  
##  3rd Qu.:1.0000   3rd Qu.:1.0000  
##  Max.   :1.0000   Max.   :1.0000
\end{verbatim}

\subsubsection{Análisis para selección de número de clusters de
individuos que alguna vez han probado
drogas}\label{analisis-para-seleccion-de-numero-de-clusters-de-individuos-que-alguna-vez-han-probado-drogas}

Se creo una gráfica tomando como variable dependiente el número de
clusters contra la suma de cuadrados dentro de los grupos, esto con la
finalidad de obtener el número que nos de un mayor volúmen de
información útil, se utilizó la metodología `elbow' para hacer una
selección.

El mejor resultado obtenido fue tomar 5 clusters, dándonos los
siguientes resultados

\includegraphics{drugs-pattern_files/figure-latex/cluster_numbers-1.pdf}

Inercia total:

\begin{verbatim}
## [1] 39772.44
\end{verbatim}

Inercia inter grupos

\begin{verbatim}
## [1] 12981.3
\end{verbatim}

Inercia intra grupos

\begin{verbatim}
## [1]  6786.811 10778.124  3881.423  2533.771  2811.016
\end{verbatim}

Inercia intra grupos (total)

\begin{verbatim}
## [1] 26791.15
\end{verbatim}

\subsubsection{Análisis de clusters para individuos que alguna vez han
probado
drogas}\label{analisis-de-clusters-para-individuos-que-alguna-vez-han-probado-drogas}

Para comprender de una mejor manera los valores que indica cada cluster,
es necesario analizar cada variable con una gráfica de caja, esto con la
intención de visualizar la manera en que se distribuyen los valores
dentro de la variable.

A continuación se muestra el análizis de cada cluster junto a su
interpretación.

\paragraph{Cluster No° 1}\label{cluster-no-1}

La interpretación del Cluster No° 1 es la siguiente:

1.- Todos los individuos han usado mariguana alguna vez.

2.- Para el uso de cocaína, crack, heroína, alucinógenos, inhalantes,
metanfetamina, calmantes de dolor, tranquilizantes, estimulantes y
sedantes, una grán mayoría afirma no haber usado estos tipos de droga,
pero a su vez para cada droga se presentan algunos casos atípicos.

3.- La cantidad de drogas probadas ronda normalmente entre 1 y 2,
presentando también algunos casos atípicos.

4.- El promedio de ingresos personales es de \$20,000 a \$29,999.

5.- El promedio de ingresos familiares es de \$40,000 a \$49,999.

6.- En promedio, los individuos tienen un empleo de tiempo completo.

7.- Predominan los individuos de raza blanca.

8.- En su mayoría los individuos cuentan con carrera trunca.

9.- Todos los individuos son mujeres.

En resumen: Grupo en su totalidad de mujeres, todas afirman haber usado
marihuana, la mayoría solo ha usado marihuana. Ingresos familiares de
clase media, pero personales de clase media-baja. Usualmente cuenta con
trabajo de tiempo completo. Se distribuyen entre raza blanca y
afroamericana, siendo la blanca predominante. Grado de estudios mínimo
de solo la preparatoria y máximo de carrera terminada, siendo carrera
trunca lo típico.

\includegraphics{drugs-pattern_files/figure-latex/cluster_1-1.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_1-2.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_1-3.pdf}

\paragraph{Cluster No° 2}\label{cluster-no-2}

La interpretación del Cluster No° 2 es la siguiente:

1.- La gran mayoría afirma haber usado marihuana, cocaína y
alucinógenos.

2.- La gran mayoría afirma no haber usado crack, heroína ni sedantes.

3.- Es común el haber usado inhalantes, meranfetaminas, tranquilizantes
y estimulantes, pero la mayoría no los ha usado.

4.- Es común el haber usado calmantes de dolor, pero la mayoría los ha
usado.

5.- La cantidad de drogas probadas ronda entre 4 y 6.

6.- Los ingresos personales en promedio rondan entre \$20,000 y
\$29,999.

7.- Los ingresos familiares en promedio rondan entre \$50,000 y
\$74,999.

8.- En promedio los individuos cuentan con un trabajo de tiempo
completo.

9.- En su gran mayoría, los individuos son de raza blanca.

10.- En promedio, los individuos cuentan con una carrera sin terminar.

11.- Predominan los hombres

En resumen: Un grupo predominado por hombres de raza blanca. El mínimo
grado de estudios es solo la preparatoria y el mayor una carrera
terminada, siendo carrera trunca lo típico, cuentan con un trabajo de
tiemplo completo. Sus ingresos familiares son de clase media-alta, pero
sus ingresos personales son de clase media-baja. Presenta un gran uso de
drogas, siendo la marihuana, cocaína y alucinógenos sus preferidos,
además es común el uso de inhalantes, metanfetaminas, tranquilizantes y
estimulantes, y aunque también es común el uso de crack, heroína y
sedantes, prefiere evitarlos.

\includegraphics{drugs-pattern_files/figure-latex/cluster_2-1.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_2-2.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_2-3.pdf}

\paragraph{Cluster No° 3}\label{cluster-no-3}

La interpretación del Cluster No° 3 es la siguiente:

1.- La gran mayoría afirma haber usado marihuana.

2.- La gran mayoría afirma no haber usado cocaína, crack, heroína,
alucinógenos, inhalantes, metanfetaminas, calmantes de dolor,
tranquilizantes, estimulantes ni sedantes.

3.- La cantidad de drogas probadas ronda entre 1 y 2, siendo 1 lo más
normal.

4.- Los ingresos personales rondan entre \$10,000 y \$19,999.

5.- Los ingresos familiares rondan entre \$30,000 - \$39,999.

6.- El promedio cuenta con un empleo de tiempo completo.

7.- Participan todas las razas, pero predominan los afroamericanos.

8.- El promedio cuenta sólo con preparatoria terminada.

9.- En su gran mayoría son hombres.

En resumen: Un grupo de todas las razas, pero en su mayoría hombres
afroamericanos de clase media-baja, normalmente cuenta con un empleo de
tiempo completo. El mínimo grado de estudios es solo la preparatoria y
el mayor carrera trunca, siendo solo la preparatoria lo típico. En su
mayoría ha usado marihuana, aunque no es común el uso de otras drogas,
no se está cerrado a la posibilidad. Sus ingresos personales son apenas
la mitad de sus ingresos familiares.

\includegraphics{drugs-pattern_files/figure-latex/cluster_3-1.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_3-2.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_3-3.pdf}

\paragraph{Cluster No° 4}\label{cluster-no-4}

La interpretación del Cluster No° 4 es la siguiente:

1.- La gran mayoría niega haber usado marihuana, cocaína, crack,
heroína, alucinógenos, metanfetaminas, tranquilizantes, estimulantes y
sedantes.

2.- Aunque es común el uso de inhalantes, la mayoría no los ha usado.

3.- Aunque es común la mayoría de calmantes de dolor, la mayoría los ha
usado.

4.- La cantidad de drogas probadas ronda entre 1 y 2, siendo 1 lo
típico.

5.- Ingresos personales promedio de entre \$20,000 y \$29,999.

6.- Ingresos familares promedio de entre \$50,000 - \$74,999.

7.- En promedio se cuenta con un empleo de medio tiempo.

8.- Se distribuyen entre raza blanca, afroamericana, nativo americano y
hawaiana, pero predomina la raza blanca.

9.- En promedio se cuenta con una carrera trunca.

10.- Grupo de ambos sexos, pero predominan las mujeres.

En resumen: Grupo predominado por mujeres, comunmente de raza blanca,
aunque también se presentan afroamericanos, nativo americanos y
hawaianos. Ingresos de clase media-alta, pero los personales son apenas
la mitad de clase media. Comunmente cuentan con un empleo de tiempo
completo y una carrera trunca. Aúnque es común el uso de inhalantes, la
mayoría no los ha usado, es común el uso de calmantes de dolor. Grado de
estudios entre sólo prepa y carrera terminada, siendo carrera trunca lo
típico.

\includegraphics{drugs-pattern_files/figure-latex/cluster_4-1.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_4-2.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_4-3.pdf}

\paragraph{Cluster No° 5}\label{cluster-no-5}

La interpretación del Cluster No° 5 es la siguiente:

1.- La gran mayoría afirma el uso de marihuana.

2.- La gran mayoría niega el uso de cocaína, crack, heroína,
alucinógenos, inhalantes, metanfetaminas, calmantes de dolor,
tranquilizantes, estimulantes y sedantes.

3.- La cantidad de drogas probadas ronda entre 1 y 2, siendo 1 lo
típico.

4.- Ingresos personales de entre \$50,000 y \$74,999.

5.- Ingresos familiares superiores a \$75,000.

6.- Comunmente el grado mínimo de estudios es con carrera trunca y el
mayor con carrera universitaria.

8.- La gran mayoría de raza blanca.

7.- Solamente hay hombres.

En resumen: Un grupo exclusivamente de hombres, en su gran mayoría de
raza blanca y clase alta, afirma sólo haber usado marihuana. El grado de
estudios está entre carrera trunca y carrera universitaria terminada.

\includegraphics{drugs-pattern_files/figure-latex/cluster_5-1.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_5-2.pdf}
\includegraphics{drugs-pattern_files/figure-latex/cluster_5-3.pdf}

\subsubsection{Diagramas de
agrupamiento}\label{diagramas-de-agrupamiento}

A continuación se presentan los diagramas de agrupamiento de clusters
según ciertas variables. Se anexa de igual forma la representación de
cada cluster.

Cluster 1: Grupo en su totalidad de mujeres, todas afirman haber usado
marihuana, la mayoría solo ha usado marihuana. Ingresos familiares de
clase media, pero personales de clase media-baja. Usualmente cuenta con
trabajo de tiempo completo. Se distribuyen entre raza blanca y
afroamericana, siendo la blanca predominante. Grado de estudios mínimo
de solo la preparatoria y máximo de carrera terminada, siendo carrera
trunca lo típico.

Cluster 2: Un grupo predominado por hombres de raza blanca. El mínimo
grado de estudios es solo la preparatoria y el mayor una carrera
terminada, siendo carrera trunca lo típico, cuentan con un trabajo de
tiemplo completo. Sus ingresos familiares son de clase media-alta, pero
sus ingresos personales son de clase media-baja. Presenta un gran uso de
drogas, siendo la marihuana, cocaína y alucinógenos sus preferidos,
además es común el uso de inhalantes, metanfetaminas, tranquilizantes y
estimulantes, y aunque también es común el uso de crack, heroína y
sedantes, prefiere evitarlos.

Cluster 3: Un grupo de todas las razas, pero en su mayoría hombres
afroamericanos de clase media-baja, normalmente cuenta con un empleo de
tiempo completo. El mínimo grado de estudios es solo la preparatoria y
el mayor carrera trunca, siendo solo la preparatoria lo típico. En su
mayoría ha usado marihuana, aunque no es común el uso de otras drogas,
no se está cerrado a la posibilidad. Sus ingresos personales son apenas
la mitad de sus ingresos familiares.

Cluster 4: Grupo predominado por mujeres, comunmente de raza blanca,
aunque también se presentan afroamericanos, nativo americanos y
hawaianos. Ingresos de clase media-alta, pero los personales son apenas
la mitad de clase media. Comunmente cuentan con un empleo de tiempo
completo y una carrera trunca. Aúnque es común el uso de inhalantes, la
mayoría no los ha usado, es común el uso de calmantes de dolor. Grado de
estudios entre sólo prepa y carrera terminada, siendo carrera trunca lo
típico.

Cluster 5: Un grupo exclusivamente de hombres, en su gran mayoría de
raza blanca y clase alta, afirma sólo haber usado marihuana. El grado de
estudios está entre carrera trunca y carrera universitaria terminada.

\paragraph{Agrupamiento por análisis de componentes
principales}\label{agrupamiento-por-analisis-de-componentes-principales}

\includegraphics{drugs-pattern_files/figure-latex/analysis_pc-1.pdf}

\paragraph{Agrupamientos por sexo}\label{agrupamientos-por-sexo}

\subparagraph{Agrupamiento de Sexo vs Cantidad de drogas
probadas}\label{agrupamiento-de-sexo-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-5-1.pdf}

\subparagraph{Agrupamiento de Sexo vs Ingresos
personales}\label{agrupamiento-de-sexo-vs-ingresos-personales}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-6-1.pdf}

\subparagraph{Agrupamiento de Sexo vs Ingresos
familiares}\label{agrupamiento-de-sexo-vs-ingresos-familiares}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-7-1.pdf}

\subparagraph{Agrupamiento de Sexo vs Estado
laboral}\label{agrupamiento-de-sexo-vs-estado-laboral}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-8-1.pdf}

\subparagraph{Agrupamiento de Sexo vs
Raza}\label{agrupamiento-de-sexo-vs-raza}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-9-1.pdf}

\subparagraph{Agrupamiento de Sexo vs Grado de
estudios}\label{agrupamiento-de-sexo-vs-grado-de-estudios}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-10-1.pdf}

\subsubsection{Agrupamientos por grado de
estudios}\label{agrupamientos-por-grado-de-estudios}

\paragraph{Agrupamiento de grado de estudios vs Cantidad de drogas
probadas}\label{agrupamiento-de-grado-de-estudios-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-11-1.pdf}

\paragraph{Agrupamiento de grado de estudios vs Ingresos
personales}\label{agrupamiento-de-grado-de-estudios-vs-ingresos-personales}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-12-1.pdf}

\paragraph{Agrupamiento de grado de estudios vs Ingresos
familiares}\label{agrupamiento-de-grado-de-estudios-vs-ingresos-familiares}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-13-1.pdf}

\paragraph{Agrupamiento de grado de estudios vs Estado
laboral}\label{agrupamiento-de-grado-de-estudios-vs-estado-laboral}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-14-1.pdf}

\paragraph{Agrupamiento de grado de estudios vs
Raza}\label{agrupamiento-de-grado-de-estudios-vs-raza}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-15-1.pdf}

\subsubsection{Agrupamientos por raza}\label{agrupamientos-por-raza}

\paragraph{Agrupamiento de Raza vs Cantidad de drogas
probadas}\label{agrupamiento-de-raza-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-16-1.pdf}

\paragraph{Agrupamiento de Raza vs Ingresos
Personales}\label{agrupamiento-de-raza-vs-ingresos-personales}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-17-1.pdf}

\paragraph{Agrupamiento de Raza vs Ingresos
Familiares}\label{agrupamiento-de-raza-vs-ingresos-familiares}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-18-1.pdf}

\paragraph{Agrupamiento de Raza vs Estado
laboral}\label{agrupamiento-de-raza-vs-estado-laboral}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-19-1.pdf}

\subsubsection{Agrupamientos por estado
laboral}\label{agrupamientos-por-estado-laboral}

\paragraph{Agrupamiento de estado laboral vs Cantidad de drogas
probadas}\label{agrupamiento-de-estado-laboral-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-20-1.pdf}

\paragraph{Agrupamiento de estado laboral vs Ingresos
personales}\label{agrupamiento-de-estado-laboral-vs-ingresos-personales}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-21-1.pdf}

\paragraph{Agrupamiento de estado laboral vs Ingresos
familiares}\label{agrupamiento-de-estado-laboral-vs-ingresos-familiares}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-22-1.pdf}

\subsubsection{Agrupamientos por ingresos
familiares}\label{agrupamientos-por-ingresos-familiares}

\paragraph{Agrupamiento de ingresos familiares vs Cantidad de drogas
probadas}\label{agrupamiento-de-ingresos-familiares-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-23-1.pdf}

\paragraph{Agrupamiento de ingresos familiares vs Ingresos
personales}\label{agrupamiento-de-ingresos-familiares-vs-ingresos-personales}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-24-1.pdf}

\subsubsection{Agrupamiento por ingresos
personales}\label{agrupamiento-por-ingresos-personales}

\paragraph{Agrupamiento de ingresos personales vs Cantidad de drogas
probadas}\label{agrupamiento-de-ingresos-personales-vs-cantidad-de-drogas-probadas}

\includegraphics{drugs-pattern_files/figure-latex/unnamed-chunk-25-1.pdf}

\section{DISCUSIÓN Y CONCLUSIONES}\label{discusion-y-conclusiones}


\end{document}
