data <- read.csv("../data/drug-test.csv")
data <- data[data$anydrugever==1,]

export.year <- data[,c("marij_year",
                       "cocaine_year",
                       "crack_year",
                       "heroin_year",
                       "hallucinogen_year",
                       "inhalant_year",
                       "meth_year",
                       "painrelieve_year",
                       "tranq_year",
                       "stimulant_year",
                       "sedative_year",
                       "countofdrugs_year",
                       "PersonalIncome",
                       "FamilyIncome",
                       "EmploymentStatus",
                       "race_num",
                       "education",
                       "sex")]

export.month <- data[,c("marij_month",
                       "cocaine_month",
                       "crack_month",
                       "heroin_month",
                       "hallucinogen_month",
                       "inhalant_month",
                       "meth_month",
                       "painrelieve_month",
                       "tranq_month",
                       "stimulant_month",
                       "sedative_month",
                       "pharmamonth",
                       "illicitmonth_nomj",
                       "countofdrugs_month",
                       "PersonalIncome",
                       "FamilyIncome",
                       "EmploymentStatus",
                       "race_num",
                       "education",
                       "sex")]

export.ever <- data[,c("marij_ever",
                       "cocaine_ever",
                       "crack_ever",
                       "heroin_ever",
                       "hallucinogen_ever",
                       "inhalant_ever",
                       "meth_ever",
                       "painrelieve_ever",
                       "tranq_ever",
                       "stimulant_ever",
                       "sedative_ever",
                       "countofdrugs_ever",
                       "PersonalIncome",
                       "FamilyIncome",
                       "EmploymentStatus",
                       "race_num",
                       "education",
                       "sex")]

write.csv(export.year, file="../data/drug-test-year.csv")
write.csv(export.month, file="../data/drug-test-month.csv")
write.csv(export.ever, file="../data/drug-test-ever.csv")
